---
title: "Program"
description: |
  국내외 R에 기여를 많이 하신 두분의 키노트 연사분을 모시고 오전 세션을 진행하고 오후는 라이브 세션과 동영상 세션이 병행하여 진행됩니다. 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# https://github.com/rstudio/distill/issues/11
xaringanExtra::use_panelset()
```

```{r google-sheet}
library(tidyverse)
# library(googlesheets4)
# googlesheets4::sheets_auth() # 구글 쉬트 인증 -----
library(lubridate)
library(readxl)

# program_tbl <- read_sheet("https://docs.google.com/spreadsheets/d/1-QujZBMXyoUSZB6IGoEF2k33-gkoJ3XmuxcN7wjmfFk/edit?usp=sharing", skip =2)

program_tbl <- read_excel("data/Program.xlsx", skip =2)

keynote_tbl <- program_tbl %>% 
  slice(1:4) %>% 
  janitor::clean_names(ascii=FALSE) %>% 
  select(시간, 프로그램) %>% 
  mutate(시간 = glue::glue("{str_pad(hour(시간), width=2, pad= 0)} : {str_pad(minute(시간), width=2, pad= 0)}"))

session_01_tbl <- program_tbl %>% 
  slice(7:10) %>%
  set_names(c("시간", "실시간 라이브", "동영상 녹화")) %>% 
  mutate(시간 = glue::glue("{str_pad(hour(시간), width=2, pad= 0)} : {str_pad(minute(시간), width=2, pad= 0)}"))

session_02_tbl <- program_tbl %>% 
  slice(13:n()) %>%
  set_names(c("시간", "실시간 라이브", "동영상 녹화")) %>% 
  mutate(시간 = glue::glue("{str_pad(hour(시간), width=2, pad= 0)} : {str_pad(minute(시간), width=2, pad= 0)}"))
```

## 환영인사 & Keynotes

```{r keynote-reactable}
# 0. 팩키지 -------------
library(tidyverse)
library(magick)
library(opencv)
library(gt)
library(readxl)

# 1. 발표자 -------
# https://statkclee.github.io/data-science/ds-rconf-profile.html

keynote <- tribble(~"구분", ~"시간", ~"발표자명", ~"소속", ~"발표제목", ~"국가", ~"파일명",
                   "오프닝", "10:00~10:15", "OOO", "OOOO", "OOOOO", "한국", "opening_speaker.png",
                   "키노트", "10:15~11:00", "Julia Silge", "RStudio", "NLP and text modeling with tidymodels", "미국", "julia_silge.png",
                   "키노트", "11:00~11:45",  "유충현", "한화생명", "Again wind in Korea with GNU R", "한국", "choonghyun_ryu.png")

keynote_tbl <- keynote %>% 
  ## ISO2 국기 -----------------------------------------
  mutate(iso2 = ifelse(국가 == "한국", "kr", "us")) %>% 
  mutate(flag_URL = glue::glue('data/worldflags/{iso2}.png')) %>% 
  ## 발표자 사진  -----------------------------------------
  mutate(파일명 = ifelse(str_detect(파일명, "datarize"), 
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.gif"),
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.png"))) %>% 
  mutate(profile_photo = glue::glue('data/speakers_mask/{파일명}')) %>% 
  ## 표에 표시할 칼럼  -----------------------------------------
  select(구분, 시간, flag_URL, profile_photo, 발표자명, 소속, 발표제목) 

keynote_tbl_gt <- keynote_tbl %>% 
  ## ISO2 국기 표에 삽입 -----------------------------------------
  gt(rowname_col = "시간", groupname_col = "구분") %>% 
  gt::text_transform(  
    locations = cells_body(columns = flag_URL),    
    fn = function(x) {
      # loop over the elements of the column
      map_chr(x, ~ local_image(
        filename = .x,
        height = 20
      ))
    }) %>%   
  # Hide column header flag_URL and reduce width
    cols_width(columns = c(flag_URL) ~ px(50)) %>% 
    cols_label(flag_URL = "") %>% 
    ## 발표자 사진 표에 삽입 -----------------------------------------
  text_transform(
    locations = cells_body(columns = c(profile_photo)),
    fn = function(x) {
      map_chr(x, ~ local_image(
        filename = .x,
        height = 50
      ))
    }) %>% 
    cols_width(columns = c(profile_photo) ~ px(100)) %>% 
    cols_label(profile_photo = "")
  

keynote_tbl_gt %>% 
  tab_header(
    title = md("**&#x2600; 한국 R 컨퍼런스 키노트 발표 &#x2600;**"),
    subtitle = md("*Make R Great Again!!!*")
  ) %>% 
  tab_source_note(
    source_note = md("**R 사용자회**: 상기 발표내용은 사정에 따라 변경될 수 있습니다.")
  ) %>% 
  tab_options(
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "32px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#ffffff",
    stub.font.weight = "bold"
  ) %>% 
  cols_align(
    align = "center",
    columns = c(flag_URL, profile_photo, 발표자명, 소속)
  ) %>%
  cols_align(
    align = "center",
    columns = 발표제목
  ) %>%  
  cols_width(
    flag_URL ~ px(50),
    profile_photo ~ px(100),
    발표자명 ~ px(100),
    소속 ~ px(150),
    발표제목 ~ px(500)
  ) %>% 
  gt::fmt_markdown(columns = `발표제목`) %>% 
  tab_style(
    style = list(
      cell_fill("#3764B0"),
      cell_text(color = "white", weight = "bold",
                align = "left",
                size = px(25))
    ),
    locations = cells_row_groups())
```


# 프로그램

::: l-page

::::: {.panelset}


::: {.panel}

## 실시간 라이브 {.panel-name}


```{r main-program, layout="l-body-outset"}
# 0. 팩키지 -------------
library(tidyverse)
library(magick)
library(opencv)
library(gt)
library(readxl)

# 1. 발표자 -------
# https://statkclee.github.io/data-science/ds-rconf-profile.html

program <- read_excel("data/발표자_대쉬보드.xlsx", sheet = "program")

program_tbl <- program %>% 
  filter(구분 == "실시간 라이브") %>% 
  ## ISO2 국기 -----------------------------------------
  mutate(iso2 = ifelse(국가 == "한국", "kr", "us")) %>% 
  mutate(flag_URL = glue::glue('data/worldflags/{iso2}.png')) %>% 
  ## 발표자 사진  -----------------------------------------
  mutate(파일명 = ifelse(str_detect(파일명, "datarize"), 
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.gif"),
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.png"))) %>% 
  mutate(profile_photo = glue::glue('data/speakers_mask/{파일명}')) %>% 
  ## 표에 표시할 칼럼  -----------------------------------------
  select(발표시간, flag_URL, profile_photo, 발표자명, 소속, 발표)  %>% 
  arrange(발표시간)
  # ## 어수행 오류 -----
  # filter(!str_detect(발표자명, "어수행|박상훈|이민호"))

program_tbl_gt <- program_tbl %>% 
  ## ISO2 국기 표에 삽입 -----------------------------------------
  gt() %>% 
  gt::text_transform(  
    locations = cells_body(columns = flag_URL),    
    fn = function(x) {
      # loop over the elements of the column
      map_chr(x, ~ local_image(
        filename = .x,
        height = 20
      ))
    }) %>%   
  # Hide column header flag_URL and reduce width
    cols_width(columns = c(flag_URL) ~ px(50)) %>% 
    cols_label(flag_URL = "") %>% 
    ## 발표자 사진 표에 삽입 -----------------------------------------
  text_transform(
    locations = cells_body(columns = c(profile_photo)),
    fn = function(x) {
      map_chr(x, ~ local_image(
        filename = .x,
        height = 50
      ))
    }) %>% 
    cols_width( flag_URL ~ px(50),
                profile_photo ~ px(70),
                발표자명 ~ px(100),
                소속 ~ px(150),
                발표 ~ px(500)
    ) %>% 
    cols_label(profile_photo = "")
  

program_tbl_gt %>% 
  tab_header(
    title = md("**&#x2600; 한국 R 컨퍼런스 프로그램 &#x2600;**"),
    subtitle = md("*NLP, 웹앱, 예측, 재현가능 과학, 산업현장, 사회과학 ...*")
  ) %>% 
  tab_source_note(
    source_note =  md("**R 사용자회**: 상기 발표내용은 사정에 따라 변경될 수 있습니다.")
  ) %>% 
  tab_options(
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "32px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#bcbddc",
    stub.font.weight = "bold"
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
    gt::fmt_markdown(columns = `발표`)

```


:::


::: {.panel}

## 동영상 녹화 {.panel-name}


```{r main-program-record, layout="l-body-outset"}
# 0. 팩키지 -------------
library(tidyverse)
library(magick)
library(opencv)
library(gt)
library(readxl)

# 1. 발표자 -------
# https://statkclee.github.io/data-science/ds-rconf-profile.html

program <- read_excel("data/발표자_대쉬보드.xlsx", sheet = "program")

program_tbl <- program %>% 
  filter(구분 == "동영상 녹화") %>% 
  ## ISO2 국기 -----------------------------------------
  mutate(iso2 = ifelse(국가 == "한국", "kr", "us")) %>% 
  mutate(flag_URL = glue::glue('data/worldflags/{iso2}.png')) %>% 
  ## 발표자 사진  -----------------------------------------
  mutate(파일명 = ifelse(str_detect(파일명, "datarize"), 
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.gif"),
                                   glue::glue("{fs::path_ext_remove(파일명)}_face_mask.png"))) %>% 
  mutate(profile_photo = glue::glue('data/speakers_mask/{파일명}')) %>% 
  ## 표에 표시할 칼럼  -----------------------------------------
  select(발표시간, flag_URL, profile_photo, 발표자명, 소속, 발표)  %>% 
  arrange(발표시간)
  # ## 어수행 오류 -----
  # filter(!str_detect(발표자명, "어수행|박상훈|이민호"))

program_tbl_gt <- program_tbl %>% 
  ## ISO2 국기 표에 삽입 -----------------------------------------
  gt() %>% 
  gt::text_transform(  
    locations = cells_body(columns = flag_URL),    
    fn = function(x) {
      # loop over the elements of the column
      map_chr(x, ~ local_image(
        filename = .x,
        height = 20
      ))
    }) %>%   
  # Hide column header flag_URL and reduce width
    cols_width(columns = c(flag_URL) ~ px(50)) %>% 
    cols_label(flag_URL = "") %>% 
    ## 발표자 사진 표에 삽입 -----------------------------------------
  text_transform(
    locations = cells_body(columns = c(profile_photo)),
    fn = function(x) {
      map_chr(x, ~ local_image(
        filename = .x,
        height = 50
      ))
    }) %>% 
    cols_width( flag_URL ~ px(50),
              profile_photo ~ px(70),
              발표자명 ~ px(100),
              소속 ~ px(150),
              발표 ~ px(500)
    ) %>% 
    cols_label(profile_photo = "")
  

program_tbl_gt %>% 
  tab_header(
    title = md("**&#x2600; 한국 R 컨퍼런스 프로그램 &#x2600;**"),
    subtitle = md("*NLP, 웹앱, 예측, 재현가능 과학, 산업현장, 사회과학 ...*")
  ) %>% 
  tab_source_note(
    source_note =  md("**R 사용자회**: 상기 발표내용은 사정에 따라 변경될 수 있습니다.")
  ) %>% 
  tab_options(
    heading.background.color = "#1E61B0", # R logo 파란색
    heading.title.font.size = "32px",
    column_labels.background.color = "#F7F7F7", # R logo 회색 
    column_labels.font.weight = "bold",
    stub.background.color = "#bcbddc",
    stub.font.weight = "bold"
  ) %>% 
  cols_align(
    align = "center",
    columns = everything()
  ) %>% 
    gt::fmt_markdown(columns = `발표`)

```

<center>


</center>

:::


:::::

:::



